name: crypto_currency
description: An application for displaying crypto currencies rates.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  clock: ^1.0.1
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  intl: ^0.16.1
  kiwi: ^0.2.0
  json_annotation: ^3.0.1
  flutter_svg: ^0.17.4
  flutter_bloc_patterns: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  kiwi_generator: ^0.4.0
  json_serializable: ^3.2.2
  lint: ^1.1.1
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/