name: crypto_currency
description: An application for displaying crypto currencies rates.
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl: ^0.16.0
  kiwi: ^0.2.0
  json_annotation: ^3.0.0
  http: ^0.12.0+2
  flutter_svg: ^0.14.2
  flutter_bloc_patterns: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  kiwi_generator: ^0.4.0
  json_serializable: ^3.2.2
  mockito: ^4.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/